# Generated by Django 5.2.16 on 2026-08-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='proposal_document',
            field=models.FileField(blank=True, help_text='Optional: upload a document with your proposal details.', null=True, upload_to='proposals/'),
        ),
    ]
