# Generated by Django 5.2.16 on 2026-08-23 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_uploaded_by'),
        ('projects', '0002_project_approval_status_project_decided_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('RESOURCE', 'Resource'), ('APPENDIX', 'Appendix'), ('GUIDELINE', 'Guideline'), ('SUPPORTING', 'Supporting Material'), ('FINAL_SUBMISSION', 'Final Submission')], default='RESOURCE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('category', 'FINAL_SUBMISSION')), fields=('project', 'uploaded_by'), name='unique_final_submission_per_student'),
        ),
    ]
